services:
  - type: web
    name: schema-forge-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PG_DB
        sync: false
      - key: PG_USER
        sync: false
      - key: PG_PASSWORD
        sync: false
      - key: PG_HOST
        sync: false
      - key: PG_PORT
        sync: false
      - key: PROJECT_NAME
        value: "schemaforge"
